- cmd/argocd/commands/app.go
Just to easily understanding what he want.
> Fix rollback command help

- ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx
- ui/src/app/shared/models.ts
- ui/src/app/shared/services/applications-service.ts
I've add "Apply Only" checkbox on Application Sync panel, that's all.
#798
> Allow Apply Only on sync

- util/grpc/grpc.go
Checklist:
closes https://github.com/argoproj/argo-cd/issues/4000
> feat: add client side keepalive pings

- pkg/apis/application/v1alpha1/types.go
- pkg/apis/application/v1alpha1/types_test.go
- util/glob/glob.go
Checklist:
Related to #3759 
Add more unit-test to explain the wildcard capabilities using `filepath.match` function.
> fix: support ** wildcard in repo sources permitted sources (#3759)

- docs/operator-manual/user-management/index.md
> chore(docs): add note about base64 encoding to SSO documentation

- util/settings/filtered_resource.go
- util/settings/resources_filter.go
- util/settings/resources_filter_test.go
Signed-off-by: darshanime <deathbullet@gmail.com>
closes https://github.com/argoproj/argo-cd/issues/4023
Checklist:
> fix: allow clusters to include resources independently

- controller/cache/cache.go
Controller uses a lot of memory during initialization because concurrent list requests are not enforced across all clusters. Current limit is enforced per cluster which is incorrect. 
Related PR: https://github.com/argoproj/gitops-engine/pull/100 . We've updated logic in gitops engine but forgot to use shared semaphore.
Closes https://github.com/argoproj/argo-cd/issues/4298
> fix: limit concurrent list requests accross all clusters

- go.mod
- go.sum
Closes #4329
Possible address #4298
> refactor: update gitops engine version (issues #4329, #4298)

- util/session/sessionmanager.go
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>
v4.0.0 release of https://github.com/dgrijalva/jwt-go had a breaking change: https://github.com/dgrijalva/jwt-go/commit/3650a7d85b04932a81f44a17b8efe27462bbbc33 . Time fields are now serialized as float instead of an integer. 
This breaks some integrations with Argo CD. Also I've checked https://tools.ietf.org/html/rfc7519#section-4.1.6 - looks like such fields should contain "number of seconds" that implies integer.
PR ensures that "date time" fields are serialized as integers.
> fix: make sure JWT token time fields contain only integer values

- docs/user-guide/application-set.md
- mkdocs.yml
Note on DCO:
If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.
Checklist:
Closes https://github.com/argoproj/argo-cd/issues/5684
> Add ApplicationSet page to Argo CD docs

- USERS.md
Note on DCO:
If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.
Checklist:
> docs: Add Ibotta to the list of users

- .github/workflows/ci-build.yaml
`dorny/paths-filter` doesn't seem to handle (multiple) negations well. Therefore, this PR switches to `tj-actions/changed-files`, since it is already successfully used in argo-workflows.
Checklist:
> chore(ci): use changed files action

- docs/developer-guide/debugging-remote-environment.md
> fix: Fix issue in starting telepresence for remote debugging (Closes #18859)

- test/container/Dockerfile
> chore: fixing dubious ownership error Closes: #18973

- server/application/terminal.go
- server/application/websocket.go
- server/application/websocket_test.go
- server/server.go
Closes #17114
Checklist:
* [ X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ X] The title of the PR states what changed and the related issues number (used for the release note).
* [ X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ X] I have written …
> fix: Exec with disable auth not logged in #17114

- USERS.md
Adding Mozilla to the USERS.md list. We have been evaluating ArgoCD for a few months and have recently started migrating production workloads to our ArgoCD instances. 
Checklist:
> docs: Add Mozilla to USERS.md

- docs/developer-guide/extensions/proxy-extensions.md
- server/extension/extension.go
- server/extension/extension_test.go
- server/server.go
- util/settings/settings.go
- util/settings/settings_test.go
> feat: allow individual extension configs

- docs/operator-manual/declarative-setup.md
I had a hard time getting the declarative setup to work when adding EKS clusters  to Argo CD. I updated the docs to clarify a few things:
1. Use Access Entries instead of depreciated `aws-auth` ConfigMap
2. Made the requirements a bit of a punch list with corresponding descriptions on each section
3. Updated Argo CD's role's example trust policy to show it needed to be able to assume itself
4. Wording updates/changes to be more specific about what examples relate to which role (etc)
5. Added a third Service Account which I believe needs to get an AWS role added to its annotation.
Checklist:
> docs: Declarative argo clusters docs update for EKS

- cmd/argocd/commands/admin/app.go
fixes part of #10592
Checklist:
> chore: improve error logs in  commands/admin/app.go

- applicationset/webhook/webhook.go
- applicationset/webhook/webhook_test.go
> fix: ApplicationSet webhooks should use stricter comparison of repository URL
