.github/no-response.yml

Use the default label `more-information-needed', because I think`question` is confusing.

more-information-needed

---

Gopkg.lock
Gopkg.toml
pkg/apis/application/v1alpha1/types_test.go
util/rbac/rbac_test.go

Checklist:
Additional:
Current version of casbin/casbin (1.5.0) contains bug – parsing policy with no-space after comma returns 'index out of range':
```
$ argocd app sync ABCD --async --grpc-web ...
FATA[0000] rpc error: code = Internal desc = runtime error: index out of range
```
```
time="2019-10-15T11:21:35Z" level=info msg="received unary call /application.ApplicationService/Sync" grpc.method=Sync grpc.request.claims="{\"iat\":1569573310,\"iss\":\"argocd\",\"nbf\":1569573310,\"sub\":\"proj:ABCD:ci-role\"}" grpc.request.content="name:\"ABCD\" revision:\"\" dryRun:false prune:false strategy:<hook:<syncStrategyApply:<force:false > > > " grpc.service=application.ApplicationService grpc.start_time="2019-10-15T11:21:35Z" span.kind=server system=grpc
time="2019-10-15T11:21:35Z" level=error …
```

Upgrade casbin/casbin to 1.9.1

---

controller/appcontroller.go
controller/sort_delete.go
controller/sort_delete_test.go

Signed-off-by: darshanime <deathbullet@gmail.com>
closes https://github.com/argoproj/argo-cd/issues/3211
Checklist:

feat: delete in reverse order of sync waves

---

manifests/base/redis/argocd-redis-deployment.yaml
manifests/install.yaml
manifests/namespace-install.yaml

We should use an image for the Redis image that doesn't
require the process to be started as root.
Checklist:
* [x ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x ] The title of the PR states what changed and the related issues number (used for the release note).
* [x ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

fix: #3933 - Use a non root Redis Image

---

docs/user-guide/ci_automation.md

Fix the ci_automation's kustomize source code in the example.
`kustomize edit set imagetag` was deleted by the [PR: Support changing of image registries in addition to image tags](https://github.com/kubernetes-sigs/kustomize/issues/402).
Checklist:
* [] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.

doc: fix the ci_automation's kustomize source code.

---

ui/src/app/applications/components/applications-list/applications-list.tsx

PR fixes javascript error on applications list page. To reproduce JS error create any application with empty destination namespace. Navigate to applications list page and try to set any namespace filter.

fix: JS error on application list page if app has no namespace

---

go.mod
go.sum

PR upgrades gitops engine.
Pulls in changes that are required for #4354 and #1787

refactor: upgrade gitops-engine version ( #4354, #1787 )

---

docs/operator-manual/high_availability.md
pkg/apis/application/v1alpha1/types.go
pkg/apis/application/v1alpha1/types_test.go
reposerver/repository/lock.go
reposerver/repository/lock_test.go
reposerver/repository/repository.go
reposerver/repository/repository_test.go

Implements first part of https://github.com/argoproj/argo-cd/issues/4583
PR changes repository server so that it executes multiple operations that require the same repository and same commit SHA ( if the operation does not change files in the repository). This in theory should significantly improve manifest generation for mono repo with many argocd apps in it.

feat: support generating manifests for the same commit in parallel

---

assets/swagger.json
cmd/argocd-util/commands/argocd_util.go
cmd/argocd-util/commands/rbac.go
cmd/argocd-util/commands/rbac_test.go
cmd/argocd-util/commands/testdata/rbac/argocd-rbac-cm.yaml
cmd/argocd-util/commands/testdata/rbac/policy.csv
docs/operator-manual/rbac.md
docs/operator-manual/server-commands/argocd-util.md
docs/operator-manual/server-commands/argocd-util_rbac.md
docs/operator-manual/server-commands/argocd-util_rbac_can.md
docs/operator-manual/server-commands/argocd-util_rbac_validate.md

Closes #4842
This PR adds a new group of commands to `argocd-util`, so that users can validate and test their RBAC policies against a local CSV file, a local YAML representation of a ConfigMap or a live ConfigMap in the cluster.
The first two new commands are:
* `argocd-util rbac can SUBJECT ACTION RESOURCE [SUB-RESOURCE]` - test whether a given subject has permissions to execute given action for given resource (and possibly, sub-resource).
* `argocd-util rbac validate` - test whether a local file contains a valid policy definition to be used by Casbin
Policy can either be given as file, using `--policy-file FILE`, or read from the current cluster context in namespace given by `--namespace NAMESPACE`. In the latter case, the name of the ConfigMap in the cluster is hard wired to …

feat: argocd-util can now validate RBAC configuration

---

server/repocreds/repocreds.go
server/repository/repository.go
util/db/db.go
util/db/db_test.go
util/db/repository.go
util/errors/credentials.go

Checklist:
Issue details: #3492

fix: Declarative helm repositories with missing secret causes all repositories in ArgoCD to lock (#3492)

---

cmd/argocd-dex/commands/argocd_dex.go
docs/operator-manual/server-commands/argocd-dex.md
docs/operator-manual/server-commands/argocd-dex_gendexcfg.md
docs/operator-manual/server-commands/argocd-dex_rundex.md
docs/user-guide/sync-options.md
server/logout/logout.go
server/logout/logout_test.go
server/server.go
server/server_test.go
util/http/http.go
util/http/http_test.go
util/oidc/oidc.go

Signed-off-by: kshamajain99 <kshamajain99@gmail.com>
closes #2917
Checklist:

fix: support longer http cookie (#2917)

---

controller/sync.go
docs/operator-manual/application.yaml
docs/user-guide/sync-options.md
go.mod
go.sum

Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>
Depends on https://github.com/argoproj/gitops-engine/pull/235
PR introduces the ability to specify resource prune propagation policy. The default stays 'foreground' but can be changed at the application level using sync option:
```yaml
syncOptions:
- PrunePropagationPolicy=foreground
```
Closes https://github.com/argoproj/argo-cd/issues/3928

feat: support resource prune propagation policy

---

util/settings/settings.go
util/settings/settings_test.go

Signed-off-by: Subba Reddy Veeramreddy <subbareddyv.uoh@gmail.com>
Fixes https://github.com/argoproj/argo-cd/issues/6401
Note on DCO:
If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.
Checklist:

feat: Ignore preserveUnknownFields in Diff from CRD Spec

---

docs/user-guide/multiple_sources.md

docs: added warning for multiple sources

---

ui/src/app/applications/components/application-create-panel/application-create-panel.tsx

Fixes #15961
This PR fixes an issue where each keystroke in the repo URL field of the "Source" panel for creating a new application triggers a call to the backend and component rerender, leading the component to feel "jumpy"
- The `<ApplicationCreatePanel />` parent component has a `<Form />` child component with a prop `formDidUpdate` 
- The value of this prop is a function that updates the desired `app` data via calling `props.onAppChanged()`
- So, each time a keystroke is entered into a form field, `app` is updated
- As `app` is passed as a prop into the child component that renders the "Revision"/"Chart" field of the "Source" panel, every keystroke will cause this field to re-render
- On the issue https://github.com/argoproj/argo-cd/issues/15961, the suggested approach is to update …

fix(ui): Fix jumpy "Source" panel when typing (issue #15961)

---

cmd/argocd-notification/commands/controller.go

Partially fix : #18642 
Checklist:

feat: Add graceful shutdown handling in notification for Issue#18642

---

docs/operator-manual/notifications/catalog.md
notifications_catalog/install.yaml
notifications_catalog/templates/app-deployed.yaml
notifications_catalog/templates/app-health-degraded.yaml
notifications_catalog/templates/app-sync-failed.yaml
notifications_catalog/templates/app-sync-running.yaml
notifications_catalog/templates/app-sync-status-unknown.yaml
notifications_catalog/templates/app-sync-succeeded.yaml

related issue: https://github.com/argoproj/argo-cd/issues/19766
fixed:
1. Notifications not being sent when `sources`  is used for multi-source applications.
- added emojis and singular - plural i.e. "Repository" "Repositories" action based on use of source and sources respectively.
Checklist:

fix: Notifications not being delivered when using sources in Application

---

applicationset/controllers/applicationset_controller.go
applicationset/controllers/applicationset_controller_test.go
docs/operator-manual/applicationset/Progressive-Syncs.md

Closes  https://github.com/argoproj/argo-cd/issues/18817.
When using Applicationset's [rolling sync](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/#rollingsync), having no steps in the manifest results in a panic. This PR attempts to fix that by ensuring a positive number of steps.
Additionally, applications not selected by MatchExpressions are still treated as part of `Step 1` (actually Step 0 due to 1-based indexing) because the `appStepMap` defaults to 0 and there is no validation for the presence in the map. 
These applications are not synced by the rolling sync. I suggest assigning them a value of `-1` to clearly indicate that they are excluded from the sync and must be manually synced.
Checklist:

fix(appset): avoid panic when no steps in rollingSync

---

cmd/argocd/commands/app.go
cmd/argocd/commands/projectwindows.go
controller/appcontroller.go
controller/sync.go
pkg/apis/application/v1alpha1/types.go
pkg/apis/application/v1alpha1/types_test.go
server/application/application.go
server/project/project.go

Cherry-picked fix: check err before use schedule and duration (https://github.com/argoproj/argo-cd/pull/20043)
fix: check err before use schedule and duration
Signed-off-by: daengdaengLee [gunho1020@gmail.com](mailto:gunho1020@gmail.com)
test: add tests for invalid schedule and duration
Signed-off-by: daengdaengLee [gunho1020@gmail.com](mailto:gunho1020@gmail.com)
feat: change to return error when sync window is invalid
Signed-off-by: daengdaengLee [gunho1020@gmail.com](mailto:gunho1020@gmail.com)
fix: use assert.Error or assert.NoError
Signed-off-by: daengdaengLee [gunho1020@gmail.com](mailto:gunho1020@gmail.com)
fix: use require instead of assert
Signed-off-by: daengdaengLee [gunho1020@gmail.com](mailto:gunho1020@gmail.com)
---------
Signed-off-by: daengdaengLee …

fix: check err before use schedule and duration (#20043)

---

docs/developer-guide/extensions/proxy-extensions.md
server/extension/extension.go
server/extension/extension_test.go
server/server.go
util/settings/settings.go
util/settings/settings_test.go

manual cherry pick of https://github.com/argoproj/argo-cd/pull/20491 fixing the conflict

feat: allow individual extension configs (#20491)

---

controller/state.go

Related to https://github.com/argoproj/argo-cd/pull/19828
Logic was changed, so this comment is not relevant anymore

chore: improve comment inside manifest-generate-paths with autosync causes an undesirable refresh sync logic

---

cmd/argocd/commands/gpg.go
cmd/argocd/commands/utils/prompt.go
cmd/argocd/commands/utils/prompt_test.go

It uses ability to configure prompts behavior inside configuration or flags. Default behavior is no promts, so we actually not affecting any existing behavior, but users can define promts to be enabled for their CLI 
Details here: 
https://github.com/argoproj/argo-cd/issues/19528
1. Default behavior 
2. Prompts enabled

feat: add prompting to confirm deletion of gpg public key

---

cmd/argocd/commands/repocreds.go

It allows for prompt behavior configuration through settings or flags. By default, prompts are disabled, ensuring no change to existing functionality. However, users can enable prompts for their CLI if desired.
Details here:
https://github.com/argoproj/argo-cd/issues/19528

feat: add prompting to confirm remove of repository credentials

---

cmd/argocd/commands/admin/backup.go
docs/user-guide/commands/argocd_admin_import.md

It allows for prompt behavior configuration through settings or flags. By default, prompts are disabled, ensuring no change to existing functionality. However, users can enable prompts for their CLI if desired.
Details here:
https://github.com/argoproj/argo-cd/issues/19528

feat: add prompting to confirm prune during backup import

---

cmd/argocd/commands/cert.go

It allows for prompt behavior configuration through settings or flags. By default, prompts are disabled, ensuring no change to existing functionality. However, users can enable prompts for their CLI if desired.
Details here:
https://github.com/argoproj/argo-cd/issues/19528

feat: add prompting to confirm delete certificate

---

util/app/path/path.go

Addresses part of https://github.com/argoproj/argo-cd/issues/11667
This PR fixes errors that happen frequently in the CI [1](https://github.com/argoproj/argo-cd/actions/runs/11494345566/job/31991806822#step:16:4377), [2](https://github.com/argoproj/argo-cd/actions/runs/11453505375/job/31866171929#step:16:10272). 
These issues arise when walking through a directory, where temporary files—like Git lock files—are scanned but may be deleted by the time their handlers execute.
Checklist:

fix(ci):  fix flaky e2e tests - ignore temporary files when checking for out of bound symlinks

---

controller/appcontroller.go
docs/operator-manual/argocd-cm.yaml
docs/operator-manual/declarative-setup.md
go.mod
go.sum
server/application/application.go
test/e2e/mask_secret_values_test.go
util/settings/settings.go
util/settings/settings_test.go

Closes https://github.com/argoproj/argo-cd/issues/15693
Implements [hide-annotations.md](https://github.com/argoproj/argo-cd/blob/master/docs/proposals/feature-bounties/hide-annotations.md) proposal.
Depends on https://github.com/argoproj/gitops-engine/pull/577
This PR adds ability to define a list of annotations to mask on secret resources. A new `resource.sensitive.mask.annotations` key (updated based on feedback on PR) is introduced in `argocd-cm` configmap which can be used to configure a list of annotation keys to mask on secret resources. 
https://github.com/user-attachments/assets/f165053d-6000-429f-9a9d-92e1650813d5
Checklist:

feat: Add ability to hide certain annotations on secret resources

---

controller/appcontroller.go
controller/metrics/metrics.go
controller/metrics/metrics_test.go

Closes: #6391 
Checklist:
For issue #6391, I have added a metric that indicates the count of orphaned resources for each application. This new metric is called `argocd_app_orphaned_resources_count{label...}` and tracks the number of orphaned resources per application.
Metric Output:

feat: add orphaned resource count metric #6391

---

manifests/base/application-controller/argocd-application-controller-statefulset.yaml
manifests/core-install.yaml
manifests/ha/install.yaml
manifests/ha/namespace-install.yaml
manifests/install.yaml
manifests/namespace-install.yaml

Closes #19474
Kube cache couldn't be used on read-only root file system leading to errors as revealed with `--gloglevel` equal to 6.
Create an empty dir mount for `/tmp` and add a config-map-based param to override `KUBECACHEDIR`.
Checklist:

chore: Add some empty dir volume mounts for the application controller (#19474)

---

common/common.go
controller/health.go
controller/health_test.go
controller/testdata/job-failed-ignore-healthcheck.yaml
docs/operator-manual/health.md

Closes https://github.com/argoproj/argo-cd/issues/19284
This PR introduces the `argocd.argoproj.io/ignore-healthcheck` annotation for an Application's immediate children. This allows the health status of these child resources to be disregarded when assessing the overall health of the Application. This is particularly useful when the unhealthiness of a child resource is acceptable and should not affect the Application's health evaluation.
Checklist:

feat(app): add ignore-healthcheck annotation

---

controller/cache/cache.go
controller/metrics/metrics.go
docs/operator-manual/high_availability.md
docs/operator-manual/metrics.md
go.mod
go.sum
util/env/env.go
util/env/env_test.go

Closes https://github.com/argoproj/argo-cd/issues/8172
Improve reconciliation performance for large clusters by avoiding resource lock contention - https://github.com/argoproj/gitops-engine/pull/629.
Checklist:

fix: avoid resources lock contention (#8172)

---

docs/operator-manual/installation.md
manifests/base/application-controller-roles/argocd-application-controller-role.yaml
manifests/core-install-with-hydrator.yaml
manifests/core-install.yaml
manifests/ha/install-with-hydrator.yaml
manifests/ha/install.yaml
manifests/ha/namespace-install-with-hydrator.yaml
manifests/ha/namespace-install.yaml
manifests/install-with-hydrator.yaml
manifests/install.yaml
manifests/namespace-install-with-hydrator.yaml
manifests/namespace-install.yaml

Upstream fix for: https://github.com/argoproj/argo-helm/issues/2974
Checklist:

fix(rbac): Add rights on applicationsets for the application controller

---

applicationset/controllers/applicationset_controller.go
applicationset/controllers/applicationset_controller_test.go

In issue https://github.com/argoproj/argo-cd/issues/19535 we have discovered a bug where ApplicationSet Progressive Sync feature gets stuck and it never recovers and get stuck forever unless you manually delete the existing `applicationsStatus` of the ApplicationSet affected or trigger a manual sync.
When the ApplicationSet is performing a progressive sync, the apps in the step being synced get the status `Pending` in the ApplicationSet `applicationStatus `. This means that the apps are gonna be synced and is waiting for the sync to start progressing.
Let's set an example, applicationset generates 3 applications. In the initial moment applicationset points to commit A
applicationset will generate those 3 applications and start the progressive sync, then application 2 is in Pending status, …

fix(applicationset): ApplicationSets with rolling sync stuck in Pending
